# This Python script is used to generate the overwrite files associated with the API docs
# The overwrite files add links to the tag and operation index files generated by the swagger parser
# Without the overwrites these index files are empty pages and look broken.
#
# To run the script, make sure you have Python 2.7 installed, and then run from the command line:
# python script_FormatOverwrites.py [path to json file to parse]
# example: python script_FormatOverwrites.py ../restapi/discovery.json

import sys
import os
import json

filepath = sys.argv[1]
tagList = []
opLists = []

if not os.path.isfile(filepath):
    print("File path {} does not exist. Exiting...".format(filepath))
    sys.exit()

with open(filepath) as json_file:
    data = json.load(json_file)
    for key, value in data['paths'].items():
        for key2, value2 in value.items():
            if 'tags' in value2:
                newTag = True
                count = 0
                for tag in tagList:
                    if value2["tags"][0] == tag:
                        newTag = False
                        opLists[count].append( value2["operationId"] )
                    count += 1
                    
                if newTag == True:
                    tagList.append( value2["tags"][0] )
                    opLists.append( [value2["operationId"]] )

    # Write the collection of overwrite files for each tag or operation
    folderPath = filepath.split('/')
    folderName = folderPath[len(folderPath)-1].split('.')

    try: os.mkdir("../specs/" + folderName[0])
    except OSError: pass

    hostVal = ''
    try: hostVal = data['host']
    except KeyError: pass
    
    baseVal = ''
    try: baseVal = data['basePath']
    except KeyError: pass

    if hostVal == '' and baseVal != '':
        if baseVal[0] == '/':
            baseVal = baseVal[1:len(baseVal)]
    
    slashStr = "/"
    if hostVal == '' and baseVal == '':
        slashStr = ""
            
    uidBase = hostVal + baseVal + slashStr + data['info']['title'] + "/" + data['info']['version']
    uidURL = uidBase.replace(" ", "%20")

    num = 0
    for name in tagList:
        f = open("../specs/" + folderName[0] + "/" + name + ".md", "w")
        f.write("---\n")
        
        f.write("uid: " + uidBase + "/tag/" + name + "\n" )
        f.write("---\n\n## Classes\n\n")
        
        for line in sorted(opLists[num]):
            f.write("[" + line + "](xref:" + uidURL + "/" + line + ")\n\n")
        f.close()
        num += 1

    # Write the main overwrite file for the root index
    f = open("../specs/" + folderName[0] + ".md", "w")
    f.write("---\n")

    f.write("uid: " + uidBase + "\n" )
    f.write( "---\n\n")
        
    f.write( data['info']['description'] + "\n\n" )

    f.write("## Classes\n\n")

    for tagName in sorted(tagList):
        linkStr = tagName.replace( " ", "%20")
        f.write( "[" + tagName + "](xref:" + uidURL + "/tag/" + linkStr + ")\n\n" )
    f.close()